GET http://localhost:8080/mvc-app/rest/v1/user/all

### !!! POST => Передаем тип Content-Type: application/json

POST http://localhost:8080/mvc-app/rest/v1/user
Content-Type: application/json

    {
      "username": "Ussser 11112",
      "email": "ur11121@mail.com",
      "password": "sdfsdfdsfdsfdsfdsf"
    }

### !!! POST => Передаем тип Content-Type: application/json

PUT http://localhost:8080/mvc-app/rest/v1/user
Content-Type: application/json

{
  "id": 13,
  "username": "Ussser 1111212121212",
  "email": "ur11121@mail.com",
  "password": "sdfsdfdsfdsfdsfdsf"
}
