GET http://localhost:8080/mvc-app/rest/v1/user/all

###
GET http://localhost:8080/mvc-app/rest/v1/user/6/id

### !!! POST => Передаем тип Content-Type: application/json (Authorization: - ААА SpringSecurity login(user01)

POST http://localhost:8080/mvc-app/rest/v1/user
Authorization: Basic user01 Qwerty123456
Content-Type: application/json

    {
      "username": "Ussser 11112",
      "email": "ur11121@mail.com",
      "password": "sdfsdfdsfdsfdsfdsf"
    }

### !!! POST => Передаем тип Content-Type: application/json

PUT http://localhost:8080/mvc-app/rest/v1/user
Content-Type: application/json

{
  "id": 13,
  "username": "Ussser 1111212121212",
  "email": "ur11121@mail.com",
  "password": "sdfsdfdsfdsfdsfdsf"
}
